services:
  db:
    image: postgres:16
    container_name: smart-budgeting-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartbudget
    volumes:
      - smart-budgeting_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - appnet

  backend:
    build:
      context: ./backend
    container_name: smart-budgeting-backend
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - appnet

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: smart-budgeting-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - appnet

volumes:
  smart-budgeting_pgdata:

networks:
  appnet:
